### ISSUE TITLE
Script todo

### ISSUE THREAD

**Issue by ninefu** [girikuncoro/distributed-web#26]
Reboot script:
- [x] update the value of rebootNum.txt
- [x] restart Tomcat

Installation script:
- [x] Write the values of F and N into a file (extra credit 1)
- [x] Support recovery from installation failure (extra credit 2):

> For up to 10 points of extra credit, modify your system (only the installation and reboot scripts need to change) to support recovery from an instance crashing in the installation script.
> 
> Basically, this can be done by making sure the steps in your installation script can be run more than once. For some steps this is trivial -- for example, installing the Tomcat server a second time does no harm. For a step that creates a file, you must make sure the step works correctly if the file already exists -- presumably just overwriting it. Steps that access SimpleDB require some care since SimpleDB supports multi-valued items.
> 
> Once your installation script has been “hardened” in this way, your reboot script can be very simple: supply your credentials, get the installation script, and re-run it.
> 
> One potential “gotcha” is that when EC2 instantiation runs your startup script as “user data” it runs as the root user, but when you ssh to an instance after rebooting it from the EC2 console you are running as ec2- user rather than root.
> 
> Submission: It is not necessary for you to demonstrate this in screenshots; it is sufficient for you to submit clearly commented copies of your installation and reboot scripts, and add any additional explanation you want to your README file.

launch script:
- [x] run this to launch N (default, 5) ec2 instances of your choosing and deploy the war file to them

Code:
- [x] Read the file containing the values of F and N
